<?php
$movies = [
	"The Godfather",
	"The Departed",
	"All Quiet on the Western Front",
	"Duck Soup",
	"The Dark Knight",
	"Fight Club",
	"Bat Man Begins",
	"The Good, the Bad and the Ugly",
	"Big Fish",
	"Raging Bull",
	"Field of Dreams",
	"The Dirty Dozen",
	"The Longest Day",
	"Star Trek",
	"The Usual Suspects",
	"Back to the Future",
	"Dumb and Dumber",
	"The Room",
	"Battlefield Earth",
	"The Incredibly Strange Creatures Who Stopped Living and Became Mixed-Up Zombies!!?",
	"Doctor Strange love or: How I Learned to Stop Worrying and Love the Bomb",
	"Doctor Strange",
	"Kill Bill",
	"You Only Live Twice", "From Russia with Love", "Gold Finger", "Thunder Ball", "On Her Majesty's Secret Service",
	"Diamonds Are Forever",
	"Live and Let Die",
	"The Man with the Golden Gun",
	"The Spy Who Loved Me",
	"Golden Eye",
	"The World is not Enough",
	"Die Another Day",
	"Quantum of Solace",
	"A Game of Thrones",
	"The Lord of the Rings",
	"Fellowship of the Ring",
	"The Two Towers",
	"Return of the King",
	"Star Wars",
	"The Phantom Menace",
	"Attack of the Clones",
	"A New Hope",
	"The Empire Strikes Back",
	"The Force Awakens",
	"The Fast and the Furious",
	"Too Fast Too Furious",
	"The Fast and the Furious: Tokyo Drift",
	"Fast and Furious",
	"Fast Five",
	"Fast and Furious Six",
	"Furious Seven",
	"The Fate of the Furious",
];
