<?php
$names = [
	['alec', 'alex', 'alexander'],
	['addie', 'addy', 'abigail', 'tabitha'],
	['arch', 'archie', 'archibald'],
	['allie', 'alice'],
	['augie', 'augustus'],
	['bab', 'babbie', 'barbara'],
	['beth', 'bess', 'bessie', 'betsey', 'betty', 'elizabeth'],
	['ben', 'benjy', 'benny', 'benjamin'],
	['bob', 'bobby', 'rob', 'robb', 'robby', 'robin', 'robert'],
	['chris', 'christan', 'christer', 'cristian', 'christopher'],
	['dick', 'rick', 'ricky', 'rich', 'richie', 'richard'],
	['dot', 'dolly', 'dorothy'],
	['fred', 'freddy', 'frederick'],
	['fanny', 'francie', 'frankie', 'frances'],
	['harry','harold', 'harris', 'harrison', 'henry'],
	['harry', 'henry', 'harold', 'harris', 'harrison'],
	['jax', 'jack', 'jacky', 'jackie', 'jacko', 'jackson'],
	['jerry', 'jeremy', 'gerald', 'jerald', 'jerrald', 'jeremiah', 'jerome'],
	['jon', 'john', 'johnny', 'john-john'],
	['larry', 'Larrie', 'lawrence', 'laurance'],
	['gina', 'gigi', 'geena', 'ginny', 'ginni', 'ginniie', 'virgi', 'virgie', 'virginia'],
	['will', 'bill', 'billy', 'willy', 'william'],
];
